/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ExamActivityRouteImport } from './routes/exam-activity'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as ItemAnalysisRouteImport } from './routes/item-analysis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as MyProgressRouteImport } from './routes/my-progress'
import { Route as ParticipationRouteImport } from './routes/participation'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as RealTimeRouteImport } from './routes/real-time'
import { Route as LocaleRoleRouteImport } from './routes/$locale.$role'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as LocaleRoleIndexRouteImport } from './routes/$locale.$role.index'
import { Route as LocaleRoleCoursesRouteImport } from './routes/$locale.$role.courses'
import { Route as LocaleRoleExamActivityRouteImport } from './routes/$locale.$role.exam-activity'
import { Route as LocaleRoleIntegrityRouteImport } from './routes/$locale.$role.integrity'
import { Route as LocaleRoleItemAnalysisRouteImport } from './routes/$locale.$role.item-analysis'
import { Route as LocaleRoleParticipationRouteImport } from './routes/$locale.$role.participation'
import { Route as LocaleRolePerformanceRouteImport } from './routes/$locale.$role.performance'
import { Route as LocaleRoleRealTimeRouteImport } from './routes/$locale.$role.real-time'
import { Route as LocaleRoleStudentsIndexRouteImport } from './routes/$locale.$role.students.index'
import { Route as LocaleRoleStudentsStudentIdRouteImport } from './routes/$locale.$role.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamActivityRoute = ExamActivityRouteImport.update({
  id: '/exam-activity',
  path: '/exam-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemAnalysisRoute = ItemAnalysisRouteImport.update({
  id: '/item-analysis',
  path: '/item-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgressRoute = MyProgressRouteImport.update({
  id: '/my-progress',
  path: '/my-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipationRoute = ParticipationRouteImport.update({
  id: '/participation',
  path: '/participation',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RealTimeRoute = RealTimeRouteImport.update({
  id: '/real-time',
  path: '/real-time',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoleRoute = LocaleRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoleIndexRoute = LocaleRoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRoleCoursesRoute = LocaleRoleCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRoleExamActivityRoute = LocaleRoleExamActivityRouteImport.update({
  id: '/exam-activity',
  path: '/exam-activity',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRoleIntegrityRoute = LocaleRoleIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRoleItemAnalysisRoute = LocaleRoleItemAnalysisRouteImport.update({
  id: '/item-analysis',
  path: '/item-analysis',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRoleParticipationRoute = LocaleRoleParticipationRouteImport.update({
  id: '/participation',
  path: '/participation',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRolePerformanceRoute = LocaleRolePerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRoleRealTimeRoute = LocaleRoleRealTimeRouteImport.update({
  id: '/real-time',
  path: '/real-time',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRoleStudentsIndexRoute = LocaleRoleStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => LocaleRoleRoute,
} as any)
const LocaleRoleStudentsStudentIdRoute =
  LocaleRoleStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => LocaleRoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/real-time': typeof RealTimeRoute
  '/$locale/$role': typeof LocaleRoleRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students/': typeof StudentsIndexRoute
  '/$locale/$role/courses': typeof LocaleRoleCoursesRoute
  '/$locale/$role/exam-activity': typeof LocaleRoleExamActivityRoute
  '/$locale/$role/integrity': typeof LocaleRoleIntegrityRoute
  '/$locale/$role/item-analysis': typeof LocaleRoleItemAnalysisRoute
  '/$locale/$role/participation': typeof LocaleRoleParticipationRoute
  '/$locale/$role/performance': typeof LocaleRolePerformanceRoute
  '/$locale/$role/real-time': typeof LocaleRoleRealTimeRoute
  '/$locale/$role/': typeof LocaleRoleIndexRoute
  '/$locale/$role/students/$studentId': typeof LocaleRoleStudentsStudentIdRoute
  '/$locale/$role/students/': typeof LocaleRoleStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/real-time': typeof RealTimeRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students': typeof StudentsIndexRoute
  '/$locale/$role/courses': typeof LocaleRoleCoursesRoute
  '/$locale/$role/exam-activity': typeof LocaleRoleExamActivityRoute
  '/$locale/$role/integrity': typeof LocaleRoleIntegrityRoute
  '/$locale/$role/item-analysis': typeof LocaleRoleItemAnalysisRoute
  '/$locale/$role/participation': typeof LocaleRoleParticipationRoute
  '/$locale/$role/performance': typeof LocaleRolePerformanceRoute
  '/$locale/$role/real-time': typeof LocaleRoleRealTimeRoute
  '/$locale/$role': typeof LocaleRoleIndexRoute
  '/$locale/$role/students/$studentId': typeof LocaleRoleStudentsStudentIdRoute
  '/$locale/$role/students': typeof LocaleRoleStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/real-time': typeof RealTimeRoute
  '/$locale/$role': typeof LocaleRoleRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students/': typeof StudentsIndexRoute
  '/$locale/$role/courses': typeof LocaleRoleCoursesRoute
  '/$locale/$role/exam-activity': typeof LocaleRoleExamActivityRoute
  '/$locale/$role/integrity': typeof LocaleRoleIntegrityRoute
  '/$locale/$role/item-analysis': typeof LocaleRoleItemAnalysisRoute
  '/$locale/$role/participation': typeof LocaleRoleParticipationRoute
  '/$locale/$role/performance': typeof LocaleRolePerformanceRoute
  '/$locale/$role/real-time': typeof LocaleRoleRealTimeRoute
  '/$locale/$role/': typeof LocaleRoleIndexRoute
  '/$locale/$role/students/$studentId': typeof LocaleRoleStudentsStudentIdRoute
  '/$locale/$role/students/': typeof LocaleRoleStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/login'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/real-time'
    | '/$locale/$role'
    | '/$locale/login'
    | '/students/$studentId'
    | '/students/'
    | '/$locale/$role/courses'
    | '/$locale/$role/exam-activity'
    | '/$locale/$role/integrity'
    | '/$locale/$role/item-analysis'
    | '/$locale/$role/participation'
    | '/$locale/$role/performance'
    | '/$locale/$role/real-time'
    | '/$locale/$role/'
    | '/$locale/$role/students/$studentId'
    | '/$locale/$role/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/login'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/real-time'
    | '/$locale/login'
    | '/students/$studentId'
    | '/students'
    | '/$locale/$role/courses'
    | '/$locale/$role/exam-activity'
    | '/$locale/$role/integrity'
    | '/$locale/$role/item-analysis'
    | '/$locale/$role/participation'
    | '/$locale/$role/performance'
    | '/$locale/$role/real-time'
    | '/$locale/$role'
    | '/$locale/$role/students/$studentId'
    | '/$locale/$role/students'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/login'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/real-time'
    | '/$locale/$role'
    | '/$locale/login'
    | '/students/$studentId'
    | '/students/'
    | '/$locale/$role/courses'
    | '/$locale/$role/exam-activity'
    | '/$locale/$role/integrity'
    | '/$locale/$role/item-analysis'
    | '/$locale/$role/participation'
    | '/$locale/$role/performance'
    | '/$locale/$role/real-time'
    | '/$locale/$role/'
    | '/$locale/$role/students/$studentId'
    | '/$locale/$role/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  CoursesRoute: typeof CoursesRoute
  ExamActivityRoute: typeof ExamActivityRoute
  IntegrityRoute: typeof IntegrityRoute
  ItemAnalysisRoute: typeof ItemAnalysisRoute
  LoginRoute: typeof LoginRoute
  ManagementRoute: typeof ManagementRoute
  MyProgressRoute: typeof MyProgressRoute
  ParticipationRoute: typeof ParticipationRoute
  PerformanceRoute: typeof PerformanceRoute
  RealTimeRoute: typeof RealTimeRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-activity': {
      id: '/exam-activity'
      path: '/exam-activity'
      fullPath: '/exam-activity'
      preLoaderRoute: typeof ExamActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item-analysis': {
      id: '/item-analysis'
      path: '/item-analysis'
      fullPath: '/item-analysis'
      preLoaderRoute: typeof ItemAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-progress': {
      id: '/my-progress'
      path: '/my-progress'
      fullPath: '/my-progress'
      preLoaderRoute: typeof MyProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participation': {
      id: '/participation'
      path: '/participation'
      fullPath: '/participation'
      preLoaderRoute: typeof ParticipationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-time': {
      id: '/real-time'
      path: '/real-time'
      fullPath: '/real-time'
      preLoaderRoute: typeof RealTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$role': {
      id: '/$locale/$role'
      path: '/$role'
      fullPath: '/$locale/$role'
      preLoaderRoute: typeof LocaleRoleRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$role/': {
      id: '/$locale/$role/'
      path: '/'
      fullPath: '/$locale/$role/'
      preLoaderRoute: typeof LocaleRoleIndexRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/courses': {
      id: '/$locale/$role/courses'
      path: '/courses'
      fullPath: '/$locale/$role/courses'
      preLoaderRoute: typeof LocaleRoleCoursesRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/exam-activity': {
      id: '/$locale/$role/exam-activity'
      path: '/exam-activity'
      fullPath: '/$locale/$role/exam-activity'
      preLoaderRoute: typeof LocaleRoleExamActivityRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/integrity': {
      id: '/$locale/$role/integrity'
      path: '/integrity'
      fullPath: '/$locale/$role/integrity'
      preLoaderRoute: typeof LocaleRoleIntegrityRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/item-analysis': {
      id: '/$locale/$role/item-analysis'
      path: '/item-analysis'
      fullPath: '/$locale/$role/item-analysis'
      preLoaderRoute: typeof LocaleRoleItemAnalysisRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/participation': {
      id: '/$locale/$role/participation'
      path: '/participation'
      fullPath: '/$locale/$role/participation'
      preLoaderRoute: typeof LocaleRoleParticipationRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/performance': {
      id: '/$locale/$role/performance'
      path: '/performance'
      fullPath: '/$locale/$role/performance'
      preLoaderRoute: typeof LocaleRolePerformanceRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/real-time': {
      id: '/$locale/$role/real-time'
      path: '/real-time'
      fullPath: '/$locale/$role/real-time'
      preLoaderRoute: typeof LocaleRoleRealTimeRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/students/': {
      id: '/$locale/$role/students/'
      path: '/students'
      fullPath: '/$locale/$role/students/'
      preLoaderRoute: typeof LocaleRoleStudentsIndexRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
    '/$locale/$role/students/$studentId': {
      id: '/$locale/$role/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/$locale/$role/students/$studentId'
      preLoaderRoute: typeof LocaleRoleStudentsStudentIdRouteImport
      parentRoute: typeof LocaleRoleRoute
    }
  }
}

interface LocaleRoleRouteChildren {
  LocaleRoleCoursesRoute: typeof LocaleRoleCoursesRoute
  LocaleRoleExamActivityRoute: typeof LocaleRoleExamActivityRoute
  LocaleRoleIntegrityRoute: typeof LocaleRoleIntegrityRoute
  LocaleRoleItemAnalysisRoute: typeof LocaleRoleItemAnalysisRoute
  LocaleRoleParticipationRoute: typeof LocaleRoleParticipationRoute
  LocaleRolePerformanceRoute: typeof LocaleRolePerformanceRoute
  LocaleRoleRealTimeRoute: typeof LocaleRoleRealTimeRoute
  LocaleRoleIndexRoute: typeof LocaleRoleIndexRoute
  LocaleRoleStudentsStudentIdRoute: typeof LocaleRoleStudentsStudentIdRoute
  LocaleRoleStudentsIndexRoute: typeof LocaleRoleStudentsIndexRoute
}

const LocaleRoleRouteChildren: LocaleRoleRouteChildren = {
  LocaleRoleCoursesRoute: LocaleRoleCoursesRoute,
  LocaleRoleExamActivityRoute: LocaleRoleExamActivityRoute,
  LocaleRoleIntegrityRoute: LocaleRoleIntegrityRoute,
  LocaleRoleItemAnalysisRoute: LocaleRoleItemAnalysisRoute,
  LocaleRoleParticipationRoute: LocaleRoleParticipationRoute,
  LocaleRolePerformanceRoute: LocaleRolePerformanceRoute,
  LocaleRoleRealTimeRoute: LocaleRoleRealTimeRoute,
  LocaleRoleIndexRoute: LocaleRoleIndexRoute,
  LocaleRoleStudentsStudentIdRoute: LocaleRoleStudentsStudentIdRoute,
  LocaleRoleStudentsIndexRoute: LocaleRoleStudentsIndexRoute,
}

const LocaleRoleRouteWithChildren = LocaleRoleRoute._addFileChildren(
  LocaleRoleRouteChildren,
)

interface LocaleRouteChildren {
  LocaleRoleRoute: typeof LocaleRoleRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleRoleRoute: LocaleRoleRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  CoursesRoute: CoursesRoute,
  ExamActivityRoute: ExamActivityRoute,
  IntegrityRoute: IntegrityRoute,
  ItemAnalysisRoute: ItemAnalysisRoute,
  LoginRoute: LoginRoute,
  ManagementRoute: ManagementRoute,
  MyProgressRoute: MyProgressRoute,
  ParticipationRoute: ParticipationRoute,
  PerformanceRoute: PerformanceRoute,
  RealTimeRoute: RealTimeRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
